---
  - name: Install Updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install OpenJDK (required by Elasticsearch and Kibana)
    apt:
      name: openjdk-11-jre-headless
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Check if Elasticsearch is already installed
    shell: dpkg -s elasticsearch
    register: elasticsearch_installed
    changed_when: false
    failed_when: elasticsearch_installed.rc not in [0, 1]
    when: ansible_distribution == "Ubuntu"

  - name: Download Elasticsearch DEB package
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.0-amd64.deb
      dest: /tmp/elasticsearch.deb
    when: ansible_distribution == "Ubuntu" and elasticsearch_installed.rc != 0

  - name: Install Elasticsearch
    apt:
      deb: /tmp/elasticsearch.deb
    when: ansible_distribution == "Ubuntu" and elasticsearch_installed.rc != 0

  - name: Gather service facts
    service_facts:

  - name: Enable and start Elasticsearch service
    service:
      name: elasticsearch
      enabled: yes
      state: started
    when: ansible_distribution == "Ubuntu" and "elasticsearch" in ansible_facts.services

  - name: Check if Kibana is already installed
    shell: dpkg -s kibana
    register: kibana_installed
    changed_when: false
    failed_when: kibana_installed.rc not in [0, 1]
    when: ansible_distribution == "Ubuntu"

  - name: Download Kibana DEB package
    get_url:
      url: https://artifacts.elastic.co/downloads/kibana/kibana-7.15.0-amd64.deb
      dest: /tmp/kibana.deb
    when: ansible_distribution == "Ubuntu" and kibana_installed.rc != 0

  - name: Install Kibana
    apt:
      deb: /tmp/kibana.deb
    when: ansible_distribution == "Ubuntu" and kibana_installed.rc != 0

  - name: Enable and start Kibana service
    service:
      name: kibana
      enabled: yes
      state: started
    when: ansible_distribution == "Ubuntu" and "kibana" in ansible_facts.services

  - name: Check if Logstash is already installed
    shell: dpkg -s logstash
    register: logstash_installed
    changed_when: false
    failed_when: logstash_installed.rc not in [0, 1]
    when: ansible_distribution == "Ubuntu"

  - name: Download Logstash DEB package
    get_url:
      url: https://artifacts.elastic.co/downloads/logstash/logstash-7.15.0-amd64.deb
      dest: /tmp/logstash.deb
    when: ansible_distribution == "Ubuntu" and logstash_installed.rc != 0

  - name: Install Logstash
    apt:
      deb: /tmp/logstash.deb
    when: ansible_distribution == "Ubuntu" and logstash_installed.rc != 0

  - name: Enable and start Logstash service
    service:
      name: logstash
      enabled: yes
      state: started
    when: ansible_distribution == "Ubuntu" and "logstash" in ansible_facts.services

